### PR TITLE
Added gitignore and gulp as req

### PR DESCRIPTION
**Pull request by Treeless**
Added gitignore and gulp as requested.

### CODE REVIEW

**Comment by Treeless** [comment]
You might still need to delete bower_components from git. Just FYI

**Comment by saviofelixmuniz** [comment]
Thank you so much, man, owe you big time :)

**Comment by Treeless** [comment]
No problem. Feel free to reach out to me if you have any other questions. Cheers.

**Comment by saviofelixmuniz** [comment]
Man, sorry to bother you again, but could you help me on one last thing?

**Comment by Treeless** [comment]
@saviofelixmuniz  Sure man. What do you need help with? :)

**Pull request merged**
