### PR TITLE
Modal fixes

### PR DESCRIPTION
**Pull request by Treeless**
I made a few changes.
* Made a modal controller for your modal. It now gets the items passed in from home controller and can display them.
* I moved bower_components out from git. Saved your libraries to bower.json
* Added a local webserver with gulp for easier development for you

Let me know if you have any other questions man. 👍

### CODE REVIEW

**Comment by saviofelixmuniz** [comment]
Man, 
Couldn't thank you enough, appreciate so much the effort you've put on this.
I had fixed it, as I've answered on stack, using the controller for the modal as well and a service for sharing data between controllers. But the gulp thing and the .gitignore are going to be both so useful for me. Just one thing, how can I run the gulp server? Is it gulp dev?
Thank you so much, man

**Comment by Treeless** [comment]
No problem man, glad to help. 

The command is as easy as just running `gulp` thats all you need. If you want to add more tasks to gulp, you can create a task and run it by doing `gulp <taskname>`. Goodluck !

**Comment by saviofelixmuniz** [comment]
Oh I see :) One more thing, since it worked over here with the service and second controller, would it be too much trouble to ask you to commit the gulp and gitignore thing so I can merge?

**Comment by Treeless** [comment]
Sure thing. Made a new branch, will submit a pull request :)

**Pull request closed without merging**
